# Generated by Django 4.2 on 2023-04-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contactPerson", "0002_rename_phone_1_contactperson_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactperson",
            name="phone",
            field=models.CharField(max_length=50),
        ),
    ]
